name: farts
favicon: null
layout_spectrum: 0.04030039184726775
typography_spectrum: 0.5960673047229648
title: The place where farts are
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.7462546429596841
  saturation: 0.25
  rhythmicContrast: 0.28432170138694346
purpose: []
